version: '2'

services:
  postgres:
    image: postgres:9.6.1
    networks:
      - opentraffic_datastore
    ports:
      - "5432:5432"
    volumes:
      - ${PGDATA}:/data
    environment:
      - POSTGRES_USER=opentraffic
      - POSTGRES_DB=opentraffic
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=opentraffic
      - PGDATA=/data/postgres

  datastore:
    image: opentraffic/datastore:latest
    networks:
      - opentraffic_datastore
    ports:
      - "8003:8003"
    volumes:
      - ${DATAPATH}:/data
    environment:
      - POSTGRES_USER=opentraffic
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=opentraffic
      - POSTGRES_HOST=postgres

networks:
  opentraffic_datastore:
    driver: bridge
